image: gcc:5.1



before_script:
  - env
  
build:
  script:
    - make
    #- curl -X POST -F "files=@testapp" "http://muzeeum.onthefive.com/api/v1/artifacts?project_id=$CI_PROJECT_ID&build_id=$CI_BUILD_ID"
  artifacts:
    untracked: true